# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('magnet', models.TextField()),
                ('req_id', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('down_date', models.DateTimeField(blank=True, null=True)),
                ('exist', models.BooleanField(default=False)),
                ('v_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
