# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tordata',
            name='resolution',
            field=models.CharField(default='720p', max_length=10),
        ),
    ]
